### ISSUE TITLE
Create a status command 

### ISSUE THREAD

**Issue by xNykram** [xNykram/music_bot#20]
Create a `!status` command that will return the following information:

![171730004-76aa6d5d-4107-4a06-9829-bc4cfa87bbb4](https://user-images.githubusercontent.com/55030025/200183128-08f6fb79-dc20-4768-8026-7594c2daa5ca.png)

where available memory is pulled from system not from container

**Comment by Hetorx** [comment]
`Available memory` means RAM memory or any other one?

**Comment by Hetorx** [comment]
One more question to you @xNykram about `Database connection`. I'm not sure I am understanding this part of task correctly. Should I create connection of MySQL with docker and then return value that we are connected or not?

**Comment by xNykram** [comment]
- RAM memory from the system
- The connection to database is already prepared, just write a util function which will test the SQLAlechemy engine (with this task I can help you) and return value for the status command (0=OK, 1=BAD).
ex. 

```
from app.db.sessions import engine
from sqlalchemy.exc import SQLAlchemyError

try: 
   engine.connect()
   # ex. return bool 0
except SQLAlchemyError as err:
   # return bool 1
```
