### ISSUE TITLE
Check if env variable exists

### ISSUE THREAD

**Issue by mateusz2173** [xNykram/music_bot#29]
Currently we have no checks for existing env variable.
For example this line from `main.py`
```python
client.run(os.environ.get("BOT_TOKEN"))
```
might fail if env variable is not set. 

Task: Add some checks and nice error message if env variable is not present.

**Comment by xNykram** [comment]
Suggestion from my side:

Create 'core' folder inside the app folder and create a settings class which will store project envs

example:

```
class Settings:(pydantic.BaseSettings):
     DEBUG: bool = os.environ.get('KEY_THAT_MIGHT_EXIST', default_value_if_key_not_available)

```

**Comment by mateusz2173** [comment]
What are pros and cons of this solution?

How can we implement error handling using this, for example if `BOT_TOKEN` isn't provided.
Do you have any idea?
@xNykram

**Comment by xNykram** [comment]
According to your example, when `BOT_TOKEN` is not provided, the method `get` will return the default value (if specified in second param). We can set the default value to `None` and connect to client only when the variable is not `None`. If the variable is set to `None` maybe we can print some log with info that the token was not specified. If the token is incorrect the discord API will raise some type of error with we can handle.

**Comment by mateusz2173** [comment]
Maybe we create some property which tells us if something is required. For example a tuple  `(key, required)`. Then if `required = True` and `key = None` we will print some error. What do you think?

**Comment by xNykram** [comment]
I would like to stick with [this](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/core/config.py) approach and create validators for variables if needed.

**Comment by mateusz2173** [comment]
seems fine for me

**Comment by mateusz2173** [comment]
@xNykram please take care of implementing your idea (no need to hurry).
You could also add error handling where we use env variables as we discussed or leave it to @Hetorx as an exercise. Decision is up to you
